name: Clean

on:
  schedule:
    # 每72小时运行一次
    - cron: '0 */72 * * *'
  workflow_dispatch:  # 也允许手动触发

# 设置必要的权限
permissions:
  actions: write  # 对actions的写入权限，用于删除工作流运行记录
  contents: read  # 对仓库内容的读取权限

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 清理Actions运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3       # 保留最近3天的记录
          keep_minimum_runs: 3  # 每个工作流至少保留3条记录
          delete_workflow_pattern: .*  # 匹配所有工作流
          delete_run_by_conclusion_pattern: success,failure,cancelled,skipped,action_required,timed_out,neutral,stale
          delete_orphan_runs: true    # 清理孤立的运行记录
          dry_run: false              # 确保实际执行删除操作
